apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sandbox-redis.fullname" . }}
  labels:
    {{- include "sandbox-redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sandbox-redis.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sandbox-redis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sandbox-redis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: sandbox-redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --appendonly
            - "yes"
            {{- if .Values.auth.enabled }}
            - --requirepass
            - $(REDIS_PASSWORD)
            {{- end }}
          ports:
            - containerPort: 6379
              name: sandbox-redis
          {{- if .Values.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.existingSecretPasswordKey }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
  {{- if .Values.master.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.master.persistence.size }}
        {{- if .Values.master.persistence.storageClass }}
        storageClassName: {{ .Values.master.persistence.storageClass }}
        {{- end }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}